<?php
$title = 'Please log in';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
<div style="border-radius:5px;margin:0 auto;border: 1px solid #CCC;width: 400px;">
<?php
    $form->setAttribute('action', $this->url('auth', array('action' => 'authenticate')));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('user'));
    echo $this->formRow($form->get('password'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    if ($this->messages){
        echo '<ul id="messages">';
        foreach($this->messages as $message)
        {
            echo '<li>'.$message.'</li>';
        }
        echo '</ul>';
    }
?>
</div>
<style>
    ul#messages{
        padding: 5px 5px 5px 25px;
        border: 1px solid #CCCCCC;
        background-color: #F6DFDF;width: 90%;
        margin: 0 auto 15px auto;
        list-style: none;
        color: rgb(131, 131, 131);
        border-radius: 5px;
    }
    form#login{padding: 20px;}
    span{display: inline-block;width: 120px;}
    input[type=text]{border-radius: 5px;border: 1px solid #CCCCCC;}
    input[type=password]{border-radius: 5px;border: 1px solid #CCCCCC;}
    label{display: block;}
</style>
